name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - gh-pages

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with: 
          ref: 'gh-pages'

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Install deployctl
        run: "deno install --allow-all --no-check -r -f https://deno.land/x/deploy/deployctl.ts"

      - name: Upload to Deno Deploy
        env: 
          DENO_TOKEN: ${{ secrets.DENO_TOKEN }}
        run: "DENO_DEPLOY_TOKEN=$DENO_TOKEN deployctl deploy --project=shoujo https://deno.land/std@0.208.0/http/file_server.ts"
