name: Update Blog

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Determine Deployment Directory
        id: determine_directory
        run: |
          day_of_week=$(date +'%u')
          if [ $day_of_week -eq 5 ]; then
            echo "::set-output name=directory::Fluid/"
          elif [ $day_of_week -eq 3 ] || [ $day_of_week -eq 6 ]; then
            echo "::set-output name=directory::Particlex/"
          elif [ $day_of_week -eq 4 ]; then
            echo "::set-output name=directory::Stellaris/"
          elif [ $day_of_week -eq 2 ] || [ $day_of_week -eq 7 ]; then
            echo "::set-output name=directory::ShokaX/"
          else # For Monday
            echo "::set-output name=directory::Diaspora/"
          fi
          
      - name: Get Current Time
        id: current_time
        run: echo "::set-output name=time::$(date +'%Y-%m-%d %H:%M:%S')"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          publish_dir: ${{ steps.determine_directory.outputs.directory }}
          github_token: ${{ secrets.DEPLOY_SECRET }}
          user_name: ${{ secrets.MY_USER_NAME }}
          user_email: ${{ secrets.MY_USER_EMAIL }}
          commit_message: "Automated Deployment at ${{ steps.current_time.outputs.time }}"