name: Update Blog

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Determine Deployment Directory
        id: determine_directory
        run: |
          day_of_week=$(date +'%u')
          if [ $day_of_week -eq 1 ] || [ $day_of_week -eq 4 ] || [ $day_of_week -eq 7 ]; then
            echo "name=directory::Fluid/" >>$GITHUB_OUTPUT
          elif [ $day_of_week -eq 2 ] || [ $day_of_week -eq 5 ]; then
            echo "name=directory::Particlex/" >>$GITHUB_OUTPUT
          else # For Wednesday and Saturday
            echo "name=directory::Stellaris/" >>$GITHUB_OUTPUT
          fi
          
      - name: Get Current Time
        id: current_time
        run: echo "name=time::$(date +'%Y-%m-%d %H:%M:%S')" >>$GITHUB_OUTPUT

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.9.3 # 使用部署到 GitHub pages 的 action
        with:
          publish_dir: ${{ steps.determine_directory.outputs.directory }} 
          github_token: ${{ secrets.DEPLOY_SECRET }} # secret 名
          user_name: ${{ secrets.MY_USER_NAME }}
          user_email: ${{ secrets.MY_USER_EMAIL }}
          commit_message: "Automated Deployment at ${{ steps.current_time.outputs.time }}" # 在 commit message 中添加当前时间
